### ISSUE TITLE
Feature request: local journal source

### ISSUE THREAD

**Issue by mducle** [disorderedmaterials/jv2#121]
Really great work!

One of my major use case for the journal viewer is to look at when old experiments were run which is great to do with the "Search across cycle -> Title" feature... _but_ this is very very slow when you run it for the first time for instruments with very large number of runs per cycles (e.g. LET) as it takes a long time to download and parse the xml files. After the first time, the data seems to be cached in memory, and this seems to also persist across invocations of `jv2` _if_ you close it and open it again a _short_ time later... if you close `jv2` and then open it a while (>1h) later it seems to lose the cache and then spends a while downloading the data again (~10min for LET).

The old JournalViewer had a option - "Preference -> Data Source -> Local Disk, Updated from Net" which I always turned on and which saved a lot of time - could this also be implemented for `jv2`, please?

Also related to the above use cases - could you make the searches case insensitive or add such an option, please?

**Comment by EthanDevlinSTFC** [comment]
implemented in v1.1

**Comment by EthanDevlinSTFC** [comment]
added in v1.1
