### ISSUE TITLE
Toggle graph series

### ISSUE THREAD

**Issue by EthanDevlinSTFC** [disorderedmaterials/jv2#131]
Re-enable original graphing features of toggleable fields and runs

**Comment by trisyoungs** [comment]
I think we shouldn't necessarily go back to the original way of doing things.  Plotting multiple SElog or runlog values on the same graph is a relatively common use case, but I think it might be better explored as an "Add data..." option on the graph widget itself. This could then bring up a list of the available SElog or runlog values for the current runs on the graph, and allow selection of additional data (one at a time) to be plotted.
