### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/jv2#28]
When we are clear of PRs, can we consider applying a more specific formatting style to the code? Ideally I'd like to replicate what we chose for Dissolve - can just grab the `.clang-format` from the root of the repo.

**Comment by EthanDevlinSTFC** [comment]
Does the presence of this file in the directory mean it is picked up and applied automatically to the downloaded clang-format? I can't see any other coded links.

**Comment by trisyoungs** [comment]
I believe `clang-format` picks up the `.clang-format` file from the directory it's run in, so as long as you're running code quality checks from the top of the repo src it should work as expected.
