### ISSUE TITLE
Catchy Code Name

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/jv2#6]
This is one issue that will no doubt persist for a while, but a new name for the project is required, since `JournalViewer` is generic, and `JournalViewer2` is just derivative.

Suggestions can be posted in the comments!

**Comment by trisyoungs** [comment]
Journal ARchive VISualser (JARVIS)

**Comment by trisyoungs** [comment]
JOUrnal Search Tool (JOUST)

**Comment by EthanDevlinSTFC** [comment]
Visualisation And Combined Charting of Experimental Data (VACCED)

**Comment by EthanDevlinSTFC** [comment]
CANVAS - (Charting ANd VisuAliSation)
CRAVAT - (ChaRting And VisuAlisaTion) ( ChaRting And VisuAlisation Tool)
JADE - (Journal Archive Data Engine)

**Comment by trisyoungs** [comment]
Closing as we're sticking with the original branding!
