### ISSUE TITLE
Displaying run number ranges

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/jv2#85]
When grouping runs together in grouped view I wonder if it would be sensible to display them ranges where possible.  So, where you currently might have:
```
72355;72356;72357;72358
```
instead this could be reformatted to display:
```
72355-72358
```

This could also be used when making requests to the backend, although I appreciate that using `-` to specify a range will conflict with the current delimiter used in the requests.

**Comment by EthanDevlinSTFC** [comment]
Issue, 
Runs grouped on same titles. These runs are not always concurrent. (see nimrod 20_3, 71160, 71201)
could have it display as it does currently. Split seperated runs into separate groups to enable this desired representation
or just accommodate for exceptions in a way like this e.g. (71115-71119, 71126-71134)

**Comment by trisyoungs** [comment]
Yep, I think group sequences where possible, and leave the rest as individual runs. Separate the lot with commas.
