### ISSUE TITLE
Don't modify base config files

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/jv2#95]
Saving table column preferences should operate on a user copy of the file rather than overwrite the one that comes packaged. There should be a mechanism to store the whole XML file in our `QSettings` object, and which is where we should attempt to load it from in the first instance - if it isn't found then revert to the default one we package.

Along similar lines, perhaps including the XML file with our default layouts etc. inside the main Qt resource file is the best option, and gives us trivial access to it when we need it.

**Comment by EthanDevlinSTFC** [comment]
QRC now used for config files now cannot be written to

**Comment by trisyoungs** [comment]
This data will have to go into the QSettings once a user has modified it for the first time. The QRC file just represents the basic, immutable config which we supply.

**Comment by EthanDevlinSTFC** [comment]
Yep, configuring all of this now
